matrix:
  include:
    - language: python
      python:
        - "3.7"
      install:
        - pip install -r python_requirements.txt
      script:
        - ./all_python_tests.sh
    - language: node_js
      node_js:
        - 12
      install:
        - cd studio
        - yarn install
        - cp travis/* .
        - cd ..
      script:
        - cd studio
        - yarn type-check
        - yarn jest
